version: "3.3"
services:
  apigateway-service:
    image: apigateway
    volumes:
      - C:\Users\CHOHYUNWOO\Desktop\Dev\local\msa-django-test\apigateway:/home/ubuntu/msa-django-test/apigateway
    ports:
      - 8000:8000
    environment:
      - PYTHONUNBUFFERED=1
    entrypoint: ["bash", "-c"]
    restart: always
    command: 
      - |
        python manage.py makemigrations --noinput
        python manage.py migrate --noinput
        python manage.py runserver 0.0.0.0:8000
    networks:
      - test
    
networks:
  test:
    external: true