# Generated by Django 3.1.3 on 2022-01-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('last_login', models.DateTimeField(verbose_name='마지막 로그인')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
